python ../evaluate/FID_In_OOD_Task.py --weightDir DIF_OOD
python ../evaluate/FID_In_OOD_Task.py --weightDir SAME_OOD
python ../evaluate/FID_In_OOD_Task.py --weightDir ALL_OOD
python ../evaluate/FID_In_OOD_Task.py --weightDir Part_OOD
python ../evaluate/FID_In_OOD_Task.py --weightDir ADD_500_OOD_IID
python ../evaluate/FID_In_OOD_Task.py --weightDir ADD_100_OOD_IID
python ../evaluate/FID_In_OOD_Task.py --weightDir ADD_50_OOD_IID
python ../evaluate/FID_In_OOD_Task.py --weightDir ADD_10_OOD_IID
python ../evaluate/FID_In_OOD_Task.py --weightDir ADD_500_OOD_ONE_CLASS
python ../evaluate/FID_In_OOD_Task.py --weightDir ADD_500_OOD_ONE_CLASS
python ../evaluate/FID_In_OOD_Task.py --weightDir ADD_500_OOD_ONE_CLASS
python ../evaluate/FID_In_OOD_Task.py --weightDir ADD_500_OOD_ONE_CLASS
